name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup GCC
      uses: Dup4/actions-setup-gcc@v1
      with:
        version: latest

    - name: Install SDL2
      uses: libsdl-org/setup-sdl@main
      id: sdl
      with:
        install-linux-dependencies: true
        version: 2-latest
    
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
